private void SqrtActionPerformed(java.awt.event.ActionEvent evt) {                                     
       double n=Double.parseDouble(output.getText());
       output.setText("√" + n + " = " + Math.sqrt(n) + "\n");
    }                                    

    private void swapActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:String a = firstField.getText();
        
        String a=output.getText();
        String b = output.getText();

       

        String temp = a;
        a = b;
        b = temp;

       output.setText("Before Swap: a = " + a +  ", After swap: b = " + b + "\n");


    }                                    

    private void SqrActionPerformed(java.awt.event.ActionEvent evt) {                                    
     double n=Double.parseDouble(output.getText());
       output.setText( n+"² = " + (n*n) + "\n");  
    }                                   

    private void cubeActionPerformed(java.awt.event.ActionEvent evt) {                                     
        double n = Double.parseDouble(output.getText());
        output.setText(n + "³ = " + (n * n * n) + "\n");
    }                                    


  //processses minutes to hours and minutes once clicked the process button"

    private void processActionPerformed(java.awt.event.ActionEvent evt) {                                        
        String input = Minutes.getText().trim();

        // Check if empty or contains non-digit characters
        if (input.isEmpty() || !input.matches("\\d+")) {
            Hours.setText("");
            Min.setText("");
            JOptionPane.showMessageDialog(this, 
                "Please enter a valid number of minutes (only digits).", 
                "Invalid Input", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Safe to convert – we already checked it's only digits
        int totalMinutes = Integer.parseInt(input);
        int hours = totalMinutes / 60;
        int remainingMinutes = totalMinutes % 60;

        Hours.setText(String.valueOf(hours));
        Min.setText(String.valueOf(remainingMinutes));
    
    }                                       

    
        public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Minutes_operation.class.getName())
                                   .log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Minutes_operation().setVisible(true);
        });
    }



    
    
    //Generate the students report card


    public Student_Report_card() {
        initComponents();
        ButtonGroup genderGroup=new ButtonGroup();
        genderGroup.add(Male);
        genderGroup.add(Female);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Number = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Male = new javax.swing.JRadioButton();
        Female = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        MCA = new javax.swing.JCheckBox();
        MscComp = new javax.swing.JCheckBox();
        MSIT = new javax.swing.JCheckBox();
        MSIS = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        javamarks = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        vb = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        average = new javax.swing.JTextField();
        Total = new javax.swing.JButton();
        Average = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        C = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Student Number");

        Number.addActionListener(this::NumberActionPerformed);

        jLabel2.setText("Student Name");

        jLabel3.setText("Gender");

        Male.setText("Male");
        Male.addActionListener(this::MaleActionPerformed);

        Female.setText("Female");

        jLabel4.setText("Degree");

        MCA.setText("MCA");

        MscComp.setText("Msc Comp");
        MscComp.addActionListener(this::MscCompActionPerformed);

        MSIT.setText("MSIT");
        MSIT.addActionListener(this::MSITActionPerformed);

        MSIS.setText("MSIS");

        jLabel5.setText("Marks in JAVA");

        jLabel6.setText("Marks in VB.NET");

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel7.setText("Total");

        total.addActionListener(this::totalActionPerformed);

        jLabel8.setText("Average");

        Total.setText("Total");
        Total.addActionListener(this::TotalActionPerformed);

        Average.setText("Average");
        Average.setToolTipText("");
        Average.addActionListener(this::AverageActionPerformed);

        jLabel9.setText("Marks in C");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MCA)
                                .addGap(61, 61, 61)
                                .addComponent(MscComp)
                                .addGap(55, 55, 55)
                                .addComponent(MSIT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                                .addComponent(MSIS)
                                .addGap(294, 294, 294))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(javamarks, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                                    .addComponent(C)
                                    .addComponent(vb)
                                    .addComponent(total, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(average))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel3)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Male)
                                .addGap(117, 117, 117)
                                .addComponent(Female))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Number, javax.swing.GroupLayout.DEFAULT_SIZE, 332, Short.MAX_VALUE)
                                .addComponent(Name)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(Average, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(294, 294, 294))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Male)
                    .addComponent(Female))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(MCA)
                    .addComponent(MscComp)
                    .addComponent(MSIT)
                    .addComponent(MSIS))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(javamarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(average, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Average)
                    .addComponent(Total))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>                        

    private void NumberActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void MscCompActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void MaleActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void MSITActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void TotalActionPerformed(java.awt.event.ActionEvent evt) {                                      
     try {
            int javaMarks = Integer.parseInt(javamarks.getText().trim());
            int vbMarks   = Integer.parseInt(vb.getText().trim());
            int cMarks    = Integer.parseInt(C.getText().trim());
            
            int totalMarks = javaMarks + vbMarks + cMarks;
            
            total.setText(String.valueOf(totalMarks));  // Fixed: use 'total' field, not button
            
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                "Please enter valid numbers in all marks fields!",
                "Invalid Input",
                JOptionPane.ERROR_MESSAGE);
            total.setText("");
        }   
    }                                     

    private void AverageActionPerformed(java.awt.event.ActionEvent evt) {                                        
        try {
            int javaMarks = Integer.parseInt(javamarks.getText().trim());
            int vbMarks   = Integer.parseInt(vb.getText().trim());
            int cMarks    = Integer.parseInt(C.getText().trim());
            
            double avg = (javaMarks + vbMarks + cMarks) / 3.0;
            
            average.setText(String.format("%.1f", avg));  // Shows one decimal like 69.0
            
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this,
                "Please enter valid numbers in all marks fields!",
                "Invalid Input",
                JOptionPane.ERROR_MESSAGE);
            average.setText("");
        }
    }                                       

    public static void main(String args[]) {

    java.awt.EventQueue.invokeLater(() -> {
        new Student_Report_card().setVisible(true);
    });
}
